### ISSUE TITLE
Log error when use with planet shine

### ISSUE THREAD

**Issue by WC12366** [linuxgurugamer/HullcamVDSContinued#23]
When use with mod planet shine, there's a strange pink square near the vessel, and the console outputs the error "NullReferenceException: Object reference not set to an instance of an object" crazily
See: PapaJoesSoup/ksp-planetshine/issues/1

**Comment by linuxgurugamer** [comment]
Would be nice to see the log errors and an image of the problem

**Comment by WC12366** [comment]
[KSP.log](https://github.com/linuxgurugamer/HullcamVDSContinued/files/4183777/KSP.log)

**Comment by linuxgurugamer** [comment]
The null refs are from Planetshine, and I can't even reproduce those.  I also need a picture showing the pink square, please

**Comment by linuxgurugamer** [comment]
Also, a save file, and/or a craft file which can show the issue

**Comment by WC12366** [comment]
ok

**Comment by WC12366** [comment]
![screenshot2](https://user-images.githubusercontent.com/41188403/74207116-287a8400-4cb9-11ea-89fd-0303feb903f6.png)

**Comment by WC12366** [comment]
> The null refs are from Planetshine, and I can't even reproduce those. I also need a picture showing the pink square, please

To reproduce those, just install hullcamera and planetshine together and launch a vessel

**Comment by WC12366** [comment]
> Also, a save file, and/or a craft file which can show the issue

but the pink square appears on any vessel

**Comment by WC12366** [comment]
and it always appears on the root part of the vessel

**Comment by linuxgurugamer** [comment]
Please provide the Player.log file.
I don't think it's Hullcam, I did extensive testing this evening.  But there are other mods which I've seen it on, I need to look at both log files

**Comment by WC12366** [comment]
but if I uninstall hullcam or planetshine, there are no null refs or the strange pink square.

**Comment by WC12366** [comment]
> Please provide the Player.log file.
> I don't think it's Hullcam, I did extensive testing this evening. But there are other mods which I've seen it on, I need to look at both log files

sorry, I don't know where the player.log is

**Comment by linuxgurugamer** [comment]
I still need the other log file,  Please run the game, and then pack all the following files:
Player.log
KSP.log
and your entire save directory, if possible

Also, I didn't recognize all those mods, could you please list where you got each one?  I may need to totally recreate an install which matches yours.
You could also zip up the entire GameData directory (do not include the Squad directores) and get that to me, would be faster.

**Comment by linuxgurugamer** [comment]
I don't knwo if you are aware of this, but you are running Planetshine 0.2.6.1, and the latest version is 0.2.6.3

Please update and see if it still happens

**Comment by WC12366** [comment]
THANKS!!!!! The pink square DISAPPEARED!!! And NO null refs in the console! thank you very much!

**Comment by linuxgurugamer** [comment]
Next time you have a problem,please post in the forums and not here.  That way you can get more people responding to you in a more timely fashion

**Comment by WC12366** [comment]
ok,thanks
