### ISSUE TITLE
Jsi External Radial-mount Camera not working? (Not an Issue)

### ISSUE THREAD

**Issue by logitechQ** [linuxgurugamer/HullcamVDSContinued#25]
Hey all the other cams work just fine but I can't get these to work for me? do they have some special keybind because I have not been able to find it in that case, I am aware of the - and = controls for the regular cameras and it works fine.

**Comment by linuxgurugamer** [comment]
No idea, there are some issues with 1.9.  I need a log file, also, questions like this are better served in the forums where other people can help
