### ISSUE TITLE
cameraClip value issue

### ISSUE THREAD

**Issue by Anomalia2022** [linuxgurugamer/HullcamVDSContinued#37]
This mod has a serious issue with the camera nearClipPlane value. 0.05 is not ideal for KSP and causes the ground to flicker and mods such as EVE-Redux (Volumetric Clouds) to not render in the camera view. It is recommended to be no lower than 0.1. I have made a cfg file fix for this as to not edit the dll but it would be for the best if the dll was 0.1 by default. I found that those who use Physics Range Extender never got the flicker bug or cloud bug because PRE had set the clip plane itself to 0.1.

Here is my cfg fix:
```
@PART[*]:HAS[@MODULE[MuMechModuleHullCamera]]:FINAL
{
	@MODULE[MuMechModuleHullCamera],*
	{
		%cameraClip = 0.1
	}
}

@PART[*]:HAS[@MODULE[MuMechModuleHullCameraZoom]]:FINAL
{
	@MODULE[MuMechModuleHullCameraZoom],*
	{
		%cameraClip = 0.1
	}

}

**Comment by linuxgurugamer** [comment]
I'll either add this patch or update the code in the next release, thanks
