### ISSUE TITLE
Improper view angles shown in VAB

### ISSUE THREAD

**Issue by KSAMissionCtrl** [linuxgurugamer/HullcamVDSContinued#8]
These two parts have offset view cones in the VAB. I notice these cones only appear when JSI Rasterprop Monitor is installed. Should it be reported over there instead? The views themselves from the parts in flight seem to be at the proper position

![untitled](https://cloud.githubusercontent.com/assets/18425575/23851649/a67ffb42-07ba-11e7-8caa-46e76980573a.png)

**Comment by linuxgurugamer** [comment]
yes, it should be reported over there

**Comment by linuxgurugamer** [comment]
Fixing it now

**Comment by linuxgurugamer** [comment]
Fixed in 0.1.9.5
